/* ============================================================
   Civil Engineering model sets — catalogue.
   Only this small file loads with the page; js/civil.js pulls a
   set's questions in on demand when the set is opened.
   Generated by qsn-all/build_civil_sets.js — do not hand-edit.
   ============================================================ */
window.CIVIL_SET_INDEX = [
    {
        key: "civil-1", n: 1, title: "Civil Model Set 1",
        subtitle: "Civil Engineering · nine subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-model-1.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 15 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 10 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-2", n: 2, title: "Civil Model Set 2",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-02.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-3", n: 3, title: "Civil Model Set 3",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-03.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-4", n: 4, title: "Civil Model Set 4",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-04.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-5", n: 5, title: "Civil Model Set 5",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-05.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-6", n: 6, title: "Civil Model Set 6",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-06.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-7", n: 7, title: "Civil Model Set 7",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-07.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-8", n: 8, title: "Civil Model Set 8",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-08.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-9", n: 9, title: "Civil Model Set 9",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-09.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-10", n: 10, title: "Civil Model Set 10",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-10.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-11", n: 11, title: "Civil Model Set 11",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-11.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-12", n: 12, title: "Civil Model Set 12",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-12.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-13", n: 13, title: "Civil Model Set 13",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-13.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-14", n: 14, title: "Civil Model Set 14",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-14.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-15", n: 15, title: "Civil Model Set 15",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-15.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 11 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-16", n: 16, title: "Civil Model Set 16",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-16.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 10 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-17", n: 17, title: "Civil Model Set 17",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-17.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 11 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-18", n: 18, title: "Civil Model Set 18",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-18.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 10 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-19", n: 19, title: "Civil Model Set 19",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-19.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 11 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-20", n: 20, title: "Civil Model Set 20",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-20.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 10 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-21", n: 21, title: "Civil Model Set 21",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-21.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 11 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-22", n: 22, title: "Civil Model Set 22",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-22.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 10 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-23", n: 23, title: "Civil Model Set 23",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-23.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 11 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-24", n: 24, title: "Civil Model Set 24",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-24.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 10 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-25", n: 25, title: "Civil Model Set 25",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-25.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 11 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-26", n: 26, title: "Civil Model Set 26",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-26.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 10 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-27", n: 27, title: "Civil Model Set 27",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-27.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 11 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-28", n: 28, title: "Civil Model Set 28",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-28.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 10 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-29", n: 29, title: "Civil Model Set 29",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-29.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 14 },
            { name: "Structural Mechanics", count: 10 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 11 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-30", n: 30, title: "Civil Model Set 30",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-30.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 10 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-31", n: 31, title: "Civil Model Set 31",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-31.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 14 },
            { name: "Structural Mechanics", count: 10 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 11 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    },
    {
        key: "civil-32", n: 32, title: "Civil Model Set 32",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-32.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 11 },
            { name: "Design of Structures", count: 10 },
            { name: "Soil Mechanics and Foundation", count: 14 },
            { name: "Basic Water Resources Engineering", count: 12 },
            { name: "Hydropower", count: 9 },
            { name: "Irrigation and Drainage", count: 10 },
            { name: "Transportation", count: 11 },
            { name: "Water Supply, Sanitation and Environment", count: 10 }
        ]
    },
    {
        key: "civil-33", n: 33, title: "Civil Model Set 33",
        subtitle: "Civil Engineering · 9 subjects",
        durationMinutes: 120, negativeMarking: 0, total: 100,
        file: "js/civil-sets/set-33.js",
        chapters: [
            { name: "Basic Civil Engineering", count: 13 },
            { name: "Structural Mechanics", count: 10 },
            { name: "Design of Structures", count: 9 },
            { name: "Soil Mechanics and Foundation", count: 13 },
            { name: "Basic Water Resources Engineering", count: 11 },
            { name: "Hydropower", count: 10 },
            { name: "Irrigation and Drainage", count: 11 },
            { name: "Transportation", count: 12 },
            { name: "Water Supply, Sanitation and Environment", count: 11 }
        ]
    }
];
